### ISSUE TITLE
是否有办法可以选择需要导入到单词本的词？

### ISSUE THREAD

**Issue by rookiezq** [yuhaowin/wordbook-bob-plugin#1]
如题，现在的实现方式是，只要翻译就增加，能否实现在翻译完可以自由选择是否导入？

**Comment by yuhaowin** [comment]
@rookiezq ,如果想要在翻译完成后自由选择是否导入，那一定需要在 bob 的 ui 上有个按钮之类的东西来触发。bob 没有提供。

现在针对句子、中文是不导入的，如果还是想导入由自己控制，那在翻译的单词后面加个标记如何？如：translate 1

这里的 1 表示 save。

**Comment by Yefee** [comment]
有没有可能通过点击收藏
<img width="35" alt="CleanShot 2023-12-31 at 00 10 47@2x" src="https://github.com/yuhaowin/wordbook-bob-plugin/assets/6420873/3a4103ff-f2b0-47d9-8450-637643877c6e">
来获取想要倒入的单词，并添加到其他词典？
