### ISSUE TITLE
提示：「认证信息」缺失

### ISSUE THREAD

**Issue by zhangwengsheng** [yuhaowin/wordbook-bob-plugin#11]
![image](https://user-images.githubusercontent.com/46594390/221742155-0f6aa1b5-a4d7-413a-b089-09295b12a970.png)

**Comment by yuhaowin** [comment]
有道还是欧路

**Comment by zhangwengsheng** [comment]
> 有道还是欧路

欧路词典

**Comment by yuhaowin** [comment]
> > 有道还是欧路
> 
> 欧路词典

<img width="477" alt="image" src="https://user-images.githubusercontent.com/34699768/221743915-3d8afb57-f482-419c-9011-925757be05f8.png">

检查一下这里是否保存成功。

**Comment by zhangwengsheng** [comment]
> > > 有道还是欧路
> > 
> > 
> > 欧路词典
> 
> <img alt="图像" width="477" src="https://user-images.githubusercontent.com/34699768/221743915-3d8afb57-f482-419c-9011-925757be05f8.png">
> 
> 检查一下这里是否保存成功。

提示 cookie 过期，但其实并没有过期，并且沙拉查词也有这个功能，我验证了一下，可以正常加入生词本。同时希望增加一个加入生词本的按钮，像沙拉查词一样，毕竟并不是每次查词都希望把他加入生词本中。
![61677568819_ pic](https://user-images.githubusercontent.com/46594390/221783067-6e3aa688-f7ae-471b-8b2a-16a8f5ba16d4.jpg)

**Comment by yuhaowin** [comment]
过期问题，这边没有复现，我用的也是欧路词典，看看是不是 token 前后有空格换行等。

**Comment by yuhaowin** [comment]
同时希望增加一个加入生词本的按钮
-------------
不支持，Bob 没有开放该接口。

**Comment by Henrrychan** [comment]
用的欧路词典。
显示cookie已过期，请重新获取。
cookie长期有效，在沙拉查词正常使用。有什么解决办法。

**Comment by oneice2020** [comment]
> 
我觉得使用「隐藏并钉到语言切换栏」可以达到类似的体验。

<img width="786" alt="image" src="https://user-images.githubusercontent.com/46884636/235729720-f574c3f2-b3d2-40fb-9d06-530b94d1f14c.png">

**Comment by oneice2020** [comment]
> ## 同时希望增加一个加入生词本的按钮
> 不支持，Bob 没有开放该接口。

我觉得使用「隐藏并钉到语言切换栏」可以达到类似的体验。

<img width="786" alt="image" src="https://user-images.githubusercontent.com/46884636/235730055-98a4cba7-0397-4312-83d4-f32674dc2f44.png">

**Comment by yuhaowin** [comment]
> > ## 同时希望增加一个加入生词本的按钮
> > 不支持，Bob 没有开放该接口。
> 
> 我觉得使用「隐藏并钉到语言切换栏」可以达到类似的体验。
> 
> <img alt="image" width="786" src="https://user-images.githubusercontent.com/46884636/235730055-98a4cba7-0397-4312-83d4-f32674dc2f44.png">

这是个新 feature ，稍后我研究一下。

**Comment by BTBMan** [comment]
@Henrrychan @zhangwengsheng 移除插件并重新添加插件 认证信息啥的最好一次填对了 我这么解决的就好了

**Comment by nb5p** [comment]
你是不是欧陆单词本的ID填错了，我刚开始使用，发现填错 ID 也会提示认证信息有问题，即使认证信息没问题。
