### ISSUE TITLE
扇贝单词添加失败

### ISSUE THREAD

**Issue by Henrrychan** [yuhaowin/wordbook-bob-plugin#13]
认证信息是对的，之前也一直都是这样用，但是突然不知道为什么添加不了。卸载插件，重下软件且没有用原来的配置文件覆盖，都无法添加单词，显示添加失败。

**Comment by yuhaowin** [comment]
是不是，扇贝的 api 发生变化了？我周末看一下吧

**Comment by yuhaowin** [comment]
我看之前的接口也是没有问题的，你检查一下是不是 auth token 过期了，同时我也更换了最新扇贝的 api，你更新一下插件再看看。

**Comment by Henrrychan** [comment]
重新更换token问题已解决，谢谢
