### ISSUE TITLE
能不能适配“不背单词”App

### ISSUE THREAD

**Issue by wyn04** [yuhaowin/wordbook-bob-plugin#14]
能不能适配“不背单词”App

**Comment by yuhaowin** [comment]
embrace pull requests.

**Comment by ursasi** [comment]
> 能不能适配“不背单词”App

不背单词每次必须20个词以上可以生成词书，使用时必须更换词书，是否符合需求

**Comment by yuhaowin** [comment]
This issue has been inactive for too long and is now closed.
