### ISSUE TITLE
欧陆词典现在只显示  是中文，无需添加

### ISSUE THREAD

**Issue by ZZZZihan** [yuhaowin/wordbook-bob-plugin#17]
![Uploading 截屏2024-09-29 10.00.06.png…]()

**Comment by ZZZZihan** [comment]
<img width="391" alt="截屏2024-09-29 10 01 59" src="https://github.com/user-attachments/assets/9a3da522-2cec-4bbb-8c2f-fd88af2032d3">

**Comment by yuhaowin** [comment]
把语言设置为英文或者自动选择
<img width="395" alt="Xnip2024-09-29_10-15-11" src="https://github.com/user-attachments/assets/e5b73e40-3569-46cb-b318-db131518681f">

**Comment by ZZZZihan** [comment]
已解决 感谢
