### ISSUE TITLE
请问能否适配添加短语呢？

### ISSUE THREAD

**Issue by WenJinGFei** [yuhaowin/wordbook-bob-plugin#18]
首先感谢作者，功能真的很好用！
医学生涉及的专有名词比较多，想添加短语会显示“中文、非英语单词无需添加单词本”
<img width="405" alt="image" src="https://github.com/user-attachments/assets/dd05fd39-aeeb-47ca-bc14-918fa95267e3">

**Comment by yuhaowin** [comment]
我周末看一下。

**Comment by yuhaowin** [comment]
@WenJinGFei 
<img width="454" alt="image" src="https://github.com/user-attachments/assets/ca6e20a4-4ffe-4200-a1cf-23c1eac72064">

**Comment by WenJinGFei** [comment]
非常感谢！！！！！
