### ISSUE TITLE
欧陆词典提升token已过期

### ISSUE THREAD

**Issue by jackMerry** [yuhaowin/wordbook-bob-plugin#2]
刚注册的欧陆账号，授权提示过期了

**Comment by yuhaowin** [comment]
我这边使用正常，请确定欧路词典的授权码是否正确。我这边的授权码中间有个空格，为了保证正确性，建议直接复制；

另外你可以用 postman 测试一下授权码是否有效。

[接口文档](https://my.eudic.net/OpenAPI/doc_api_study#-studylistapi-addcategory)

**Comment by yuhaowin** [comment]
另外，你可以查询一下，是否有 id = 0 的单词本。

![image](https://user-images.githubusercontent.com/34699768/111282146-a5c0b700-8678-11eb-9c4a-c79c86b67aad.png)

**Comment by fky** [comment]
> 另外，你可以查询一下，是否有 id = 0 的单词本。
> 
> ![image](https://user-images.githubusercontent.com/34699768/111282146-a5c0b700-8678-11eb-9c4a-c79c86b67aad.png)

[下载装个客户端](https://www.eudic.net/v4/en/app/download)，登录账号后会创建id=0的生词本

在[web后台](https://my.eudic.net/studyList)，或api创建的生词本，id都是>0

**Comment by yuhaowin** [comment]
原来如此，我以为所有用户都会有一个 id =0 的单词本，就在代码里把这个 id 写死了，代码在 main.js 里：

![image](https://user-images.githubusercontent.com/34699768/113691402-f3bc5e00-96fe-11eb-94b4-86a164090752.png)

**Comment by yuhaowin** [comment]
v0.1.4 支持指定单词本ID，第一次未填写ID时，会获取所有可用的单词本。

![Xnip2021-06-22_10-31-11](https://user-images.githubusercontent.com/34699768/122853589-0b41d500-d345-11eb-8e83-74aeac87d345.png)
