### ISSUE TITLE
非常好使，非常感谢～但是有个小建议

### ISSUE THREAD

**Issue by 1tonsilla** [yuhaowin/wordbook-bob-plugin#20]
能否有手动选项，是否自动添加到单词本里，因为有的单词只是单纯看一下，并不想加到单词本里

再次非常感谢，鲍勃有救了 哈哈

**Comment by yuhaowin** [comment]
可以使用**总是折叠**模式实现。
<img width="889" alt="image" src="https://github.com/user-attachments/assets/1a9b8ee5-e25b-4e05-8629-ec7069f19ffc" />
