### ISSUE TITLE
欧路词典 token 错误或过期，请重新填写

### ISSUE THREAD

**Issue by Passio2002** [yuhaowin/wordbook-bob-plugin#21]
您好
我已经更新了token，其他插件的使用也没有问题，但提示“欧路词典 token 错误或过期，请重新填写”。这是什么问题呢？谢谢回复。
祝好

**Comment by yuhaowin** [comment]
我这边可以正常使用，请确认 token 输入框前后是否有空格等。

**Comment by Passio2002** [comment]
您好，我确认无误，而且点“验证”显示验证成功。

**Comment by yuhaowin** [comment]
OK 周末我看一下。

**Comment by yuhaowin** [comment]
- [ ] 请填写正确的**欧路单词本 id**。
- [ ] 请再次确认 token 是否正确，**注意 token 是有空格的**，请直接复制使用。


<img width="535" alt="image" src="https://github.com/user-attachments/assets/2a6aaaa6-ddc4-4981-b393-6605b8ae86f7" />

**Comment by Passio2002** [comment]
已解决，谢谢！

**Comment by yuhaowin** [comment]
> 已解决，谢谢！

ok, 可更新 v0.2.3，该版本优化了欧路词典参数的验证逻辑。
