### ISSUE TITLE
扇贝单词添加失败

### ISSUE THREAD

**Issue by DreamsCat** [yuhaowin/wordbook-bob-plugin#6]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/52805134/169218420-bc734a6f-3148-4e1c-9a74-5c20b4abd742.png">
在扇贝首页找到 auth_token，复制进去，然后保存。

翻译单词，提示添加单词失败.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/52805134/169218511-a2048a71-816b-48e5-b6c6-aaaddf9d5c89.png">

**Comment by yuhaowin** [comment]
please update the lastest version, and just support save word.

![215634](https://image.yuhaowin.com/2022/05/19/215634.png)
